Add code to debug Omaha 4 update failures on macOS

diff --git a/patches/chrome-updater-mac-.install.sh.patch b/patches/chrome-updater-mac-.install.sh.patch
--- a/patches/chrome-updater-mac-.install.sh.patch
+++ b/patches/chrome-updater-mac-.install.sh.patch
@@ -1,5 +1,5 @@
 diff --git a/chrome/updater/mac/.install.sh b/chrome/updater/mac/.install.sh
-index 3b1874d09fca0cf88e361927dfea7c4273790030..a1b6a4fb30123dfd26ff22aad6c5a208e9777f09 100755
+index 3b1874d09fca0cf88e361927dfea7c4273790030..f2d4a4c9eec54857b07cf6442b78535bc584006d 100755
 --- a/chrome/updater/mac/.install.sh
 +++ b/chrome/updater/mac/.install.sh
 @@ -322,7 +322,7 @@ main() {
@@ -20,3 +20,27 @@ index 3b1874d09fca0cf88e361927dfea7c4273790030..a1b6a4fb30123dfd26ff22aad6c5a208
    note "update_app = ${update_app}"
  
    # Make sure that it's an absolute path.
+@@ -455,6 +455,12 @@ main() {
+   # directory unusable even for an instant.
+   if [[ -n "${update_versioned_dir}" ]]; then
+     note "rsyncing versioned directory"
++    local debug_flags=0
++    if [[ ! -d "${new_versioned_dir}" ]]; then
++      debug_flags=1
++      mkdir -p "${new_versioned_dir}" && (( debug_flags |= 2 ))
++      rm -rf "${new_versioned_dir}"
++    fi
+     if ! rsync ${RSYNC_FLAGS} --delete-before "${update_versioned_dir}/" \
+                                               "${new_versioned_dir}"; then
+       err "rsync of versioned directory failed, status ${PIPESTATUS[0]}"
+@@ -463,7 +469,9 @@ main() {
+       # The incomplete version would break code signature validation.
+       note "cleaning up new_versioned_dir"
+       rm -rf "${new_versioned_dir}"
+-      exit 12
++      rsync ${RSYNC_FLAGS} --delete-before "${update_versioned_dir}" "${installed_versions_dir}" && (( debug_flags |= 4 ))
++      rm -rf "${new_versioned_dir}"
++      exit $((17 + debug_flags))
+     fi
+   fi
+ 
