Revamp linux upload apt/rpm scripts
Makes changes to the upload scripts necessary for switching signing over
to a second subkey.

References: https://github.com/brave/devops/issues/1073
Fixes: https://github.com/brave/brave-browser/issues/6522
Fixes: https://github.com/brave/devops/issues/464
Fixes: https://github.com/brave/devops/issues/1995
Fixes: https://github.com/brave/devops/issues/1988

diff --git a/script/upload_to_rpm_repo b/script/upload_to_rpm_repo
--- a/script/upload_to_rpm_repo
+++ b/script/upload_to_rpm_repo
@@ -14,60 +14,59 @@ set -exu
 #
 # Date          Channel       Fingerprint           Full Key
 #
+# NOT ACTIVE    Release       0xA8580BDC82D3DC6C    9BD198A2D848C482E3550697A8580BDC82D3DC6C
 # 06/26/2019    Release       0x4FE13824E3FFC656    E85FFA8E2E90B40B33ED39274FE13824E3FFC656
 # 12/29/2018    Beta          0x0B31DBA06A8A26F9    9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9
 # 12/29/2018    Dev           0x0B31DBA06A8A26F9    9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9
 # 12/29/2018    Nightly       0x0B31DBA06A8A26F9    9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9
 
-BUCKET=${1:-brave-browser-rpm-staging-nightly}
-GPG_KEY_ID=${2:-D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821} # Defaults to New Brave Software signing key
-GPG_KEY_SHORT_ID=${GPG_KEY_ID:(-8)}
+S3_BUCKET=${1}
+GPG_KEY_ID=${2}
+TMP_REPO=$(mktemp -d)
+# SNAP_TAG=$(date +'%s')
 
-if [ -z "${CHANNEL}" ]; then
-    echo "Error: Environment variable CHANNEL not set! Exitting..."
+if [ -n "$S3_BUCKET" ]; then
+    echo "Error: Please pass the S3 bucket argument as the first argument"
     exit 1
 fi
 
-if [[ $2 == 0x* ]]; then
-    echo "Error: Please pass the Full GPG KEY ID to sign with! (i.e. 'E85FFA8E2E90B40B33ED39274FE13824E3FFC656')"
+if [ -n "$GPG_KEY_ID" ]; then
+    echo "Error: Please pass the full GPG Key ID as the second argument"
     exit 1
 fi
 
-if [ "$GPG_KEY_ID" = "E85FFA8E2E90B40B33ED39274FE13824E3FFC656" ]; then
-  KEY_NAME=brave-core.asc
-else
-  KEY_NAME=brave-core-nightly.asc
-fi
-KEY_FILE=/tmp/${KEY_NAME}
-TMP_REPO=/tmp/rpm_repo
+case "$GPG_KEY_ID" in
+    "D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821"|"9BD198A2D848C482E3550697A8580BDC82D3DC6C"|"E85FFA8E2E90B40B33ED39274FE13824E3FFC656")  # Release keys
+        KEY_NAME=brave-core.asc
+        ;;
+    "9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9") # Nightly key
+        KEY_NAME=brave-core-nightly.asc
+        ;;
+    *)
+        echo "Error! Unknown key passed in. Bailing out."
+        exit 1
+        ;;
+esac
+
+# Kill the old gpg agent
+echo KILLAGENT | gpg-connect-agent
+
+# Unlock the GPG signing key (timeout 10 minutes)
+set +x # Re-enable +x to hide passphrase from debug output
+echo | gpg2 --batch --pinentry-mode loopback --passphrase "$GPG_PASS" --sign > /dev/null
+set -x # Undo
 
 echo "%_signature gpg
 %_gpg_path $HOME/.gnupg
 %_gpg_name Brave Software
 %_gpgbin /usr/bin/gpg" > ~/.rpmmacros
 
-rm -rf $TMP_REPO
-mkdir -pv $TMP_REPO/x86_64
-
-# if .sig files exist remove them
-rm -rf dist/*.sig
-
-# Check whether each rpm is signed
-for i in $(ls dist/*.rpm); do
-    if ! rpm -v -K $i | grep "key ID ${GPG_KEY_SHORT_ID,,}: OK"; then
-        if [ "${CHANNEL}" = "release" ]; then
-            echo "No signature found, running \"./rpm-resign.exp $GPG_KEY_ID $i (REDACTED GPG_PASSPHRASE)\""
-            ./rpm-resign.exp $GPG_KEY_ID $i $GPG_PASSPHRASE
-            # removes passphrase from gpg-agent cache
-            # to prevent rpm-resign.exp failure due
-            # to an error like:
-            # send: spawn id exp4 not open
-            #     while executing
-            # "send -- $PASSPHRASE\r"
-            echo RELOADAGENT | gpg-connect-agent
-        else
-            rpm --resign $i
-        fi
+rm -rf "$TMP_REPO"
+mkdir -pv "$TMP_REPO/x86_64"
+for package in dist/*.rpm; do
+    if ! (rpm --checksig "$package" | grep "signatures OK$"); then
+        rpmsign --delsign "$package"
+	rpmsign --addsign --key-id="$GPG_KEY_ID!" "$package"
     fi
 done
 
@@ -75,19 +74,12 @@ done
 # NOTE: rpm displays the short key id, all lower case
 rpm -v -K dist/*.rpm | grep "key ID ${GPG_KEY_SHORT_ID,,}: OK"
 
-# if .sig files exist remove them
-rm -rf dist/*.sig
-
-cp dist/*.rpm $TMP_REPO/x86_64/
+cp dist/*.rpm "$TMP_REPO/x86_64/"
 
 for arch in $TMP_REPO/x86_64 ; do
-	createrepo -v --deltas $arch/
-done
-for arch in $TMP_REPO/x86_64 ; do
-	createrepo -v --update --deltas $arch/
+	createrepo -v --deltas "$arch/"
+	createrepo -v --update --deltas "$arch/"
 done
 
-gpg --export --armor ${GPG_KEY_ID} > ${KEY_FILE}
-aws s3 cp ${KEY_FILE} s3://${BUCKET}/${KEY_NAME}
-aws s3api put-object-acl --acl public-read --bucket ${BUCKET} --key ${KEY_NAME}
-aws s3 sync --acl public-read $TMP_REPO/ s3://$BUCKET/
+gpg --export --armor "${GPG_KEY_ID}!" | aws s3 cp --acl public-read - "s3://${S3_BUCKET}/${KEY_NAME}"
+aws s3 sync --acl public-read "$TMP_REPO/" "s3://{$S3_BUCKET}/"
