Only accept the full GPG key ID when signing linux packages

diff --git a/script/upload_to_rpm_repo b/script/upload_to_rpm_repo
--- a/script/upload_to_rpm_repo
+++ b/script/upload_to_rpm_repo
@@ -16,6 +16,12 @@ set -exu
 BUCKET=${1:-brave-browser-rpm-staging-nightly}
 GPG_KEY_ID=${2:-E85FFA8E2E90B40B33ED39274FE13824E3FFC656} # Defaults to New Brave Software signing key
 GPG_KEY_SHORT_ID=${GPG_KEY_ID:(-8)}
+
+if [[ $2 == 0x* ]]; then
+    echo "Error: Please pass the Full GPG KEY ID to sign with! (i.e. '9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9')"
+    exit 1
+fi
+
 if [ "$GPG_KEY_ID" = "E85FFA8E2E90B40B33ED39274FE13824E3FFC656" ]; then
   KEY_NAME=brave-core.asc
 else
