Revamp linux upload apt/rpm scripts
Makes changes to the upload scripts necessary for switching signing over
to a second subkey.

References: https://github.com/brave/devops/issues/1073
Fixes: https://github.com/brave/brave-browser/issues/6522
Fixes: https://github.com/brave/devops/issues/464
Fixes: https://github.com/brave/devops/issues/1995
Fixes: https://github.com/brave/devops/issues/1988

diff --git a/script/upload_to_aptly b/script/upload_to_aptly
--- a/script/upload_to_aptly
+++ b/script/upload_to_aptly
@@ -12,31 +12,41 @@ set -exu
 # DOESN'T HAVE A SIGNING SUBKEY.
 #
 # Date          Channel       Fingerprint           Full Key
-#
 # 06/26/2019    Release       0x0BB75829C2D4E821    D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821
 # 12/29/2018    Beta          0x0B31DBA06A8A26F9    9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9
 # 12/29/2018    Dev           0x0B31DBA06A8A26F9    9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9
 # 12/29/2018    Nightly       0x0B31DBA06A8A26F9    9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9
 
 ### The first argument is the S3 bucket, the second is the GPG key fingerprint
-OPTION=${1:-brave-browser-apt-staging-nightly}
-GPG_KEY_ID=${2:-D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821} # Defaults to New Brave Software signing key
+S3_BUCKET=${1}
+GPG_KEY_ID=${2}
+DIST='artful zesty yakkety xenial jessie trusty serena stretch bionic buster cosmic disco eoan bullseye stable'
+# SNAP_TAG=$(date +'%s')
 
-if [[ $2 == 0x* ]]; then
-    echo "Error: Please pass the Full GPG KEY ID to sign with! (i.e. '9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9')"
+if [ -n "$S3_BUCKET" ]; then
+    echo "Error: Please pass the S3 bucket argument as the first argument"
     exit 1
 fi
 
-if [ "$GPG_KEY_ID" = "D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821" ]; then
-  KEY_NAME=brave-core.asc
-else
-  KEY_NAME=brave-core-nightly.asc
+if [ -n "$GPG_KEY_ID" ]; then
+    echo "Error: Please pass the full GPG Key ID as the second argument"
+    exit 1
 fi
-KEY_FILE=/tmp/${KEY_NAME}
-SNAP_TAG=`date +'%s'`
-DIST='artful zesty yakkety xenial jessie trusty serena stretch bionic buster cosmic disco bullseye'
 
-cat <<EOF > $HOME/.aptly.conf
+case "$GPG_KEY_ID" in 
+    "D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821"|"9BD198A2D848C482E3550697A8580BDC82D3DC6C"|"E85FFA8E2E90B40B33ED39274FE13824E3FFC656")  # Release keys
+        KEY_NAME=brave-core.asc
+        ;;
+    "9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9") # Nightly key
+        KEY_NAME=brave-core-nightly.asc
+        ;;
+    *)
+        echo "Error! Unknown key passed in. Bailing out."
+        exit 1
+        ;;
+esac
+
+cat <<EOF > "$HOME/.aptly.conf"
 {
   "rootDir": "$HOME/.aptly",
   "downloadConcurrency": 4,
@@ -101,38 +111,25 @@ EOF
 # Make sure staging and release cache isn't mixed
 rm -Rf ~/.aptly
 
-gpg --export --armor ${GPG_KEY_ID} > ${KEY_FILE}
-aws s3 cp ${KEY_FILE} s3://${OPTION}/${KEY_NAME}
-aws s3api put-object-acl --acl public-read --bucket ${OPTION} --key ${KEY_NAME}
+gpg --export --armor "${GPG_KEY_ID}!" | aws s3 cp --acl public-read - "s3://${S3_BUCKET}/${KEY_NAME}" # key suffix ! forces gpg to use the specified key
 
-for i in ${DIST}
-	do aptly publish drop -force-drop $i s3:${OPTION}: || true
+for i in ${DIST}; do
+	aptly publish drop -force-drop "$i" "s3:${S3_BUCKET}:" || true
+	aptly repo drop -force "${i}-release" || true
+	aptly snapshot drop -force "${i}-snapshot" || true
+	aptly repo create -distribution="$i" -component=main "${i}-release"
+	aptly repo add "${i}-release" dist/*.deb
+	aptly snapshot create "${i}-snapshot" from repo "${i}-release"
+	aptly repo edit "${i}-release"
 done
 
-for i in ${DIST}
-	do aptly repo drop -force ${i}-release || true
-done
+# TODO: Add some sanity checks for the repos
 
-for i in ${DIST}
-	do aptly snapshot drop -force ${i}-snapshot || true
+set +x
+for i in ${DIST}; do
+	if [ "${i}" = "stable" ]; then 
+        STABLE_ARGS="-origin='Brave Software' -label='Brave Browser'"
+    fi
+	aptly publish snapshot ${STABLE_ARGS} -force-overwrite=true -gpg-key="${GPG_KEY_ID}!" -passphrase="${GPG_PASS}" "${i}-snapshot" "s3:${S3_BUCKET}:"
 done
-
-for i in ${DIST}
-	do aptly repo create -distribution=$i -component=main ${i}-release
-done
-
-for i in ${DIST}
-	do aptly repo add ${i}-release dist/*.deb
-done
-
-for i in ${DIST}
-	do aptly snapshot create ${i}-snapshot from repo ${i}-release
-done
-
-for i in ${DIST}
-	do aptly repo edit ${i}-release
-done
-
-for i in ${DIST}
-	do aptly publish snapshot -force-overwrite=true -gpg-key=${GPG_KEY_ID} ${i}-snapshot s3:${OPTION}:
-done
+set -x
