Ensure rpms have been signed

diff --git a/script/upload_to_rpm_repo b/script/upload_to_rpm_repo
--- a/script/upload_to_rpm_repo
+++ b/script/upload_to_rpm_repo
@@ -18,6 +18,11 @@ BUCKET=${1:-brave-browser-rpm-staging-nightly}
 GPG_KEY_ID=${2:-E85FFA8E2E90B40B33ED39274FE13824E3FFC656} # Defaults to New Brave Software signing key
 GPG_KEY_SHORT_ID=${GPG_KEY_ID:(-8)}
 
+if [ -z "${CHANNEL}" ]; then
+    echo "Error: Environment variable CHANNEL not set! Exitting..."
+    exit 1
+fi
+
 if [[ $2 == 0x* ]]; then
     echo "Error: Please pass the Full GPG KEY ID to sign with! (i.e. '9228DBCE20DDE5EC46488DE90B31DBA06A8A26F9')"
     exit 1
@@ -38,13 +43,35 @@ echo "%_signature gpg
 
 rm -rf $TMP_REPO
 mkdir -pv $TMP_REPO/x86_64
-if ! rpm --checksig dist/*.rpm | grep OK; then
-  ./auto_rpm_sign
-  rpm --checksig dist/*.rpm | grep OK
-fi
+
+# if .sig files exist remove them
+rm -rf dist/*.sig
+
+# Check whether each rpm is signed
+for i in $(ls dist/*.rpm); do
+    if ! rpm -v -K $i | grep "key ID ${GPG_KEY_SHORT_ID,,}: OK"; then
+        if [ "${CHANNEL}" = "release" ]; then
+            echo "No signature found, running \"./rpm-resign.exp $GPG_KEY_ID $i (REDACTED GPG_PASSPHRASE)\""
+            ./rpm-resign.exp $GPG_KEY_ID $i $GPG_PASSPHRASE
+            # removes passphrase from gpg-agent cache
+            # to prevent rpm-resign.exp failure due
+            # to an error like:
+            # send: spawn id exp4 not open
+            #     while executing
+            # "send -- $PASSPHRASE\r"
+            echo RELOADAGENT | gpg-connect-agent
+        else
+            rpm --resign $i
+        fi
+    fi
+done
+
 # Ensure the rpm has the correct signature before continuing
 # NOTE: rpm displays the short key id, all lower case
 rpm -v -K dist/*.rpm | grep "key ID ${GPG_KEY_SHORT_ID,,}: OK"
+
+# if .sig files exist remove them
+rm -rf dist/*.sig
 
 cp dist/*.rpm $TMP_REPO/x86_64/
 
