Switch to `gh pr`. Sed for printing.

diff --git a/.github/workflows/require-checklist.yml b/.github/workflows/require-checklist.yml
--- a/.github/workflows/require-checklist.yml
+++ b/.github/workflows/require-checklist.yml
@@ -14,10 +14,7 @@ jobs:
           REPO_NAME: ${{ github.event.repository.full_name }}
           PR_NUMBER: ${{ github.event.number }}
         run: |
-          function grep_no_match_ok() {
-            local exit_code
-            grep "$@" || exit_code=$?
-            return $((exit_code == 1 ? 0 : exit_code))
-          }
-          unchecked=$(gh api repos/"$REPO_NAME"/issues/"$PR_NUMBER" --jq '.body' | awk '/## Reviewer Checklist/,/## After-merge Checklist/' | grep_no_match_ok '\[ \]')
-          [ -n "$unchecked" ] && echo "Found unchecked reviewer items. Failing..." && echo "$unchecked" && exit 1 || :
+          if gh pr view "$PR_NUMBER" -R "$REPO_NAME" --json body --jq '.body' | sed -n '/## Reviewer Checklist/,/## After-merge Checklist/p' | grep '\[ \]'; then
+              echo "Found unchecked reviewer items. Failing..."
+              exit 1
+          fi
